name: Deploy Frontend

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy frontend to VPS
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd /root/MSaver.Frontend
                      git fetch origin
                      git reset --hard origin/master

                      cd /root/MSaver.Deploy
                      docker compose up -d --build frontend
